DROP SEQUENCE IF EXISTS question_seq;
CREATE SEQUENCE question_seq START WITH 1 INCREMENT by 1;

DROP SEQUENCE IF EXISTS student_seq;
CREATE SEQUENCE student_seq START WITH 1 INCREMENT by 1;

DROP SEQUENCE IF EXISTS subject_seq;
CREATE SEQUENCE subject_seq START WITH 1 INCREMENT by 1;
